#
# Makefile for the QCOM spcific video device drivers
# based on V4L2.
#

obj-$(CONFIG_MSM_VIDC_V4L2)     += vidc/
obj-$(CONFIG_MSM_WFD) += wfd/
#Charm start
#obj-y += broadcast/
obj-$(CONFIG_DVB_MPQ) += dvb/
#obj-$(CONFIG_MSMB_CAMERA) += camera_v2/
obj-y += camera_v2/
#Charm end
obj-$(CONFIG_MSM_VPU) += vpu/
