#
# Makefile for the Linux Kernel SOC specific device drivers.
#
#Charm
##obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-y		+= qcom/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_SOC_TI)		+= ti/
obj-$(CONFIG_PLAT_VERSATILE)	+= versatile/
